@startuml
database Client
database Intermediary
database Payer
Client -> Intermediary : PAS Request
Payer -> Intermediary : X12N 278 Response
Intermediary -> Client : PAS Complete Response
Intermediary -[#0000FF]-> Client : PAS Pended Response
Client -[#0000FF]-> Intermediary : PAS Subscription Request
Intermediary -[#0000FF]-> Payer : X12N 278i Request
Payer -[#0000FF]-> Intermediary : X12N 278i Response
Intermediary -[#0000FF]-> Client : PAS Subscription Response
@enduml
