# ╭────────────────────────ImplementationGuide-hl7.fhir.us.davinci-pas.json────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-pas
canonical: http://hl7.org/fhir/us/davinci-pas
version: 2.2.0-ballot
name: DaVinciPriorAuthorizationSupport
title: Da Vinci Prior Authorization Support (PAS) FHIR IG
status: active
publisher: 
  name: HL7 International / Financial Management
  url: http://hl7.org/Special/committees/fm
  email: fmlists@lists.hl7.org
contact:
  - name: Jean Duteau
    telecom:
      - system: email
        value: mailto:jean@duteaudesign.com
  - name: HL7 International / Financial Management
    telecom:
      - system: url
        value: http://www.hl7.org/Special/committees/fm
description: Guidelines for conveying coverage requirements to clinicians when planning treatment.
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core.v311:
    version: 3.1.1
    uri: http://hl7.org/fhir/us/core/v311/ImplementationGuide/hl7.fhir.us.core.v311
    id: uscore3
    reason: |
      Needed for systems supporting USCDI v1
  hl7.fhir.us.core.v610:
    version: 6.1.0
    uri: http://hl7.org/fhir/us/core/v610/ImplementationGuide/hl7.fhir.us.core.v610
    id: uscore6
    reason: |
      Needed for systems supporting USCDI v3
  hl7.fhir.us.core:
    version: 7.0.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: uscore7
    reason: |
      Needed for systems supporting USCDI v4
  hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.uv.sdc: 3.0.0
  hl7.fhir.us.davinci-crd:
    version: 2.1.0
    id: crd
  hl7.fhir.us.davinci-hrex:
    uri: http://hl7.org/fhir/us/davinci-hrex/ImplementationGuide/hl7.fhir.us.davinci-hrex
    version: 1.1.0
    id: hrex
  hl7.fhir.uv.subscriptions-backport.r4:
    version: 1.1.0
    id: subscriptions
  hl7.fhir.us.carin-bb:
    version: 2.1.0
    id: carinbb
parameters:
  show-inherited-invariants: false
  path-expansion-params: '../../exp-params.json'
  auto-oid-root: 2.16.840.1.113883.4.642.40.24
  apply-publisher: true
  apply-contact: true
  globals-in-artifacts: true
  pin-canonicals: pin-multiples
  version-comparison: 
   - 2.1.0
  shownav: true
copyrightYear: 2020+
releaseLabel: STU 2.2
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 3
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: fm 
pages:
  index.md:
    title: Prior Authorization Implementation Guide Home Page
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
  usecases.md:
    title: Use Cases and Overview
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
  additionalinfo.md:
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
    title: Request for Additional Information
  background.md:
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
    title: Technical Background
  regulations.md:
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
    title: HIPAA Regulations
  specification.md:
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
    title: Formal Specification
  privacy.md:
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
    title: Privacy & Security
  epaWorkflow.md:
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
    title: PAS ePA Coordinator Information
  metrics.md:
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
    title: PAS Metrics
  downloads.md:
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
    title: Downloads
  credits.md:
    title: Credits
  fhirArtifacts.md:
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
    title: Artifacts Overview
  changelog.md:
    title: Change Log
  conformance.md:
    title: Conformance

menu:
  IG Home: index.html
  Background:
    Reading this IG: background.html
    Use Cases: usecases.html
    Project and Participants: credits.html
    ePA Coordinator: epaWorkflow.html
  Specification:
    Conformance Expectations: conformance.html
    Technical Specification: specification.html
    Request for Additional Info: additionalinfo.html
    HIPAA Regulations: regulations.html
    Privacy, Safety, and Security: privacy.html
    Metrics: metrics.html
  FHIR Artifacts:
    Overview: fhirArtifacts.html
    Artifacts: artifacts.html
  Base Specs:
    FHIR R4 Spec: new-tab {{site.data.fhir.path}}
    US Core 3.1.1: new-tab {{site.data.fhir.ver.uscore3}}
    US Core 6.1.0: new-tab {{site.data.fhir.ver.uscore6}}
    US Core 7.0.0: new-tab {{site.data.fhir.ver.uscore7}}
    HRex 1.1.0: new-tab {{site.data.fhir.ver.hrex}}
    CRD: new-tab {{site.data.fhir.ver.crd}}
    Subscription Backport: new-tab {{site.data.fhir.ver.subscriptions}}
  Support:
    Discussion Forum: https://chat.fhir.org/#narrow/stream/208874-Da-Vinci-PAS
    Project Page: https://confluence.hl7.org/pages/viewpage.action?pageId=42993876
    Implementer Support: https://confluence.hl7.org/display/DVP/PAS+Implementer+Support
    Specification Dashboard: https://jira.hl7.org/secure/Dashboard.jspa?selectPageId=11813
    Propose a Change: https://jira.hl7.org/secure/CreateIssueDetails!init.jspa?pid=10405&amp;issuetype=10600&amp;customfield_11302=FHIR-us-davinci-pas
    Downloads: downloads.html
  Change Log: changelog.html
  History: http://hl7.org/fhir/us/davinci-pas/history.html
