# ╭────────────────────────ImplementationGuide-hl7.fhir.us.davinci-pas.json────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-pas
canonical: http://hl7.org/fhir/us/davinci-pas
version: 1.0.0
name: DaVinciPriorAuthorizationSupport
title: Da Vinci Prior Authorization Support (PAS) FHIR IG
status: active
publisher: 
  name: HL7 International - Financial Management Work Group
  url: http://hl7.org/Special/committees/fm
  email: fmlists@lists.hl7.org
contact:
  - name: Jean Duteau
    telecom:
      - system: email
        value: mailto:jean@duteaudesign.com
description: Guidelines for conveying coverage requirements to clinicians when planning
  treatment.
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 3.1.0
parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: CI Build
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
pages:
  index.md:
    title: Prior Authorization Implementation Guide Home Page
  usecases.md:
    title: Use Cases and Overview
  background.md:
    title: Technical Background
  regulations.md:
    title: HIPAA Regulations
  specification.md:
    title: Formal Specification
  downloads.md:
    title: Downloads
  credits.md:
    title: Credits
  fhirArtifacts.md:
    title: Artifacts Overview

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To control the ig.ini using this config, uncomment and set the "template" property.           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
template: hl7.davinci.template

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Table of Contents: toc.html
  PAS Specification:
    PAS Home Page: index.html
    Use Cases and Overview: usecases.html
    Technical Background: background.html
    HIPAA Regulations: regulations.html
    Formal Specification: specification.html
    Downloads: downloads.html
    Credits: credits.html
  FHIR Artifacts: fhirArtifacts.html
  Base Specs:
    FHIR R4 Spec: new-tab {{site.data.fhir.path}}
    US Core: new-tab {{site.data.fhir.ver.hl7_fhir_us_core}}
  History: http://hl7.org/fhir/us/davinci-pas/history.html
